### ISSUE TITLE
Incorrect link in Step 1

### ISSUE THREAD

**Issue by ninaszymor** [raspberrypilearning/project-showcase#11]
Looks like the link to 'Project Showcase' starting point in Step 1, the 'Club leader notes' section is incorrect - it takes you to the mystery letter starting point. The link in 'Project materials' and in Step 2 is different (correct).

![image](https://user-images.githubusercontent.com/33628387/41407884-b5c5718c-6fc8-11e8-8ea0-ac03e70c42e7.png)

**Comment by martinohanlon** [comment]
I have fixed the urls across all the different tranlations see #14 .
