### ISSUE TITLE
Changes to trinket mean step 4 is out of date

### ISSUE THREAD

**Issue by ninaszymor** [raspberrypilearning/project-showcase#16]
Hi all,

My volunteers have pointed out that the following sentence in step 4 - and the screenshot that follows it - are out of date due to changes in Trinket interface:

![image](https://user-images.githubusercontent.com/33628387/43574630-9ff3f1b8-963c-11e8-82e0-4effa9f7d43b.png)

This is what it is now:

![image](https://user-images.githubusercontent.com/33628387/43575254-4df0a67a-963e-11e8-8e50-54e709f201de.png)

**Comment by ninaszymor** [comment]
@martinohanlon the changes you made will appear in Crowdin so we will get them translated - once that's done, I will fix the other language versions we currently have live.

Let's keep this issue open for now so I don't forget ;-)

**Comment by martinohanlon** [comment]
@ninaszymor - did you forget?
