### ISSUE TITLE
Links need updating

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/project-showcase#21]
The links in the screenshots throughout the project refer to codeclub.org.uk and need updating to codeclub.org

**Comment by martinohanlon** [comment]
Unfortunately we cant update to use `codeclub.org` as it doesnt allow connections from iframes outside the codeclub.org domain.

**Comment by martinohanlon** [comment]
![image](https://user-images.githubusercontent.com/2329501/52220243-52bf8780-2896-11e9-83a9-49343c555587.png)

**Comment by martinohanlon** [comment]
resolved
